/**
 * Local keyword-based category detection. Runs synchronously on every
 * keystroke in the add-expense form — no API call, no LLM, no network.
 *
 * Coverage is intentionally India-skewed (Swiggy, Zomato, Blinkit, Ola,
 * Rapido, IRCTC, BookMyShow…) since that's where the user base lives.
 *
 * Matching is whole-word boundary on lowercase text. The first rule that
 * fires wins, so order rules narrowest → broadest.
 */

import type { CategoryKey } from "./categories";

type Rule = { keywords: string[]; category: CategoryKey };

const RULES: Rule[] = [
  // Food
  {
    category: "food",
    keywords: [
      "swiggy",
      "zomato",
      "uber eats",
      "ubereats",
      "blinkit dinner",
      "kfc",
      "mcdonald",
      "mcd",
      "domino",
      "subway",
      "starbucks",
      "ccd",
      "dunkin",
      "burger king",
      "pizza",
      "burger",
      "sushi",
      "noodles",
      "ramen",
      "biryani",
      "biriyani",
      "thali",
      "samosa",
      "dosa",
      "idli",
      "vada",
      "paratha",
      "naan",
      "kebab",
      "tandoori",
      "chai",
      "tea",
      "coffee",
      "espresso",
      "latte",
      "snack",
      "snacks",
      "lunch",
      "dinner",
      "breakfast",
      "brunch",
      "supper",
      "meal",
      "restaurant",
      "cafe",
      "café",
      "cafeteria",
      "diner",
      "bistro",
      "eatery",
      "ice cream",
      "icecream",
      "dessert",
      "bakery",
      "pastry",
      "cake",
      "donut",
      "doughnut",
      "pani puri",
      "chaat",
      "pav bhaji",
      "chinese",
      "thai",
      "italian",
      "mexican",
      "sandwich",
      "wrap",
    ],
  },

  // Travel
  {
    category: "travel",
    keywords: [
      // Ride-hailing + cabs
      "uber",
      "ola",
      "rapido",
      "blablacar",
      "auto",
      "auto rickshaw",
      "rickshaw",
      "taxi",
      "cab",
      "carpool",
      "ride",
      // Personal vehicles (the original miss — these are common
      // expense descriptions for fuel / service / rental etc).
      "car",
      "bike",
      "motorbike",
      "motorcycle",
      "scooter",
      "scooty",
      "activa",
      "bullet",
      "royal enfield",
      "rental",
      "car rental",
      "bike rental",
      "zoomcar",
      "drivezy",
      "bounce",
      "yulu",
      "vogo",
      // Public transport
      "metro",
      "local",
      "bus",
      "redbus",
      "ksrtc",
      "bmtc",
      "best",
      // Air
      "flight",
      "flights",
      "airline",
      "indigo",
      "spicejet",
      "vistara",
      "air india",
      "akasa",
      // Rail
      "train",
      "irctc",
      "tatkal",
      "rajdhani",
      "shatabdi",
      // Fuel + road
      "petrol",
      "diesel",
      "fuel",
      "gas station",
      "iocl",
      "hpcl",
      "bpcl",
      "shell",
      "indian oil",
      "bharat petroleum",
      "hindustan petroleum",
      "toll",
      "fastag",
      "parking",
      "garage",
      "vehicle service",
      "service centre",
      "service center",
      "transport",
      "boarding pass",
      "ticket booking",
    ],
  },

  // Stay
  {
    category: "stay",
    keywords: [
      "airbnb",
      "booking.com",
      "agoda",
      "trivago",
      "makemytrip",
      "goibibo",
      "yatra",
      "cleartrip",
      "oyo",
      "treebo",
      "fabhotel",
      "hotel",
      "resort",
      "homestay",
      "lodge",
      "stay",
      "hostel",
      "accommodation",
      "guest house",
      "guesthouse",
      "villa",
      "cottage",
      "bnb",
    ],
  },

  // Groceries
  {
    category: "groceries",
    keywords: [
      "blinkit",
      "zepto",
      "instamart",
      "bigbasket",
      "dmart",
      "d-mart",
      "reliance fresh",
      "more retail",
      "spencer",
      "natures basket",
      "grocery",
      "groceries",
      "vegetable",
      "vegetables",
      "veggies",
      "fruit",
      "fruits",
      "milk",
      "bread",
      "rice",
      "atta",
      "flour",
      "dal",
      "pulses",
      "oil",
      "ghee",
      "butter",
      "eggs",
      "cheese",
      "yogurt",
      "curd",
      "spice",
      "spices",
      "produce",
      "supermarket",
      "kirana",
      "supermart",
    ],
  },

  // Bills
  {
    category: "bills",
    keywords: [
      "electricity",
      "elec bill",
      "bescom",
      "tneb",
      "msedcl",
      "water bill",
      "bwssb",
      "gas bill",
      "lpg",
      "indane",
      "hp gas",
      "internet",
      "wifi",
      "broadband",
      "act fibernet",
      "jiofiber",
      "airtel xstream",
      "phone bill",
      "mobile recharge",
      "postpaid",
      "prepaid",
      "rent",
      "monthly rent",
      "maintenance",
      "society",
      "society fee",
      "cleaning",
      "maid",
      "cook",
      "househelp",
      "house help",
      "laundry",
      "dhobi",
      "dry clean",
      "dry cleaning",
    ],
  },

  // Entertainment
  {
    category: "entertainment",
    keywords: [
      "movie",
      "movies",
      "cinema",
      "concert",
      "show",
      "play",
      "theatre",
      "theater",
      "netflix",
      "spotify",
      "apple music",
      "amazon prime",
      "disney",
      "hotstar",
      "youtube premium",
      "youtube music",
      "game",
      "games",
      "gaming",
      "playstation",
      "xbox",
      "steam",
      "ticket",
      "tickets",
      "bookmyshow",
      "pvr",
      "inox",
      "imax",
      "bowling",
      "club",
      "nightclub",
      "bar",
      "pub",
      "lounge",
      "drinks",
      "cocktail",
      "alcohol",
      "beer",
      "wine",
      "whiskey",
      "rum",
      "vodka",
      "gin",
      "tequila",
      "party",
      "birthday",
      "celebration",
      "anniversary",
    ],
  },
];

const ESCAPE = /[.*+?^${}()|[\]\\]/g;

// Pre-compile a single regex per rule for fast matching. Uses \b word
// boundaries so "tea" doesn't match "stealing", and case-insensitive flag.
const COMPILED = RULES.map((rule) => ({
  category: rule.category,
  pattern: new RegExp(
    `\\b(?:${rule.keywords
      .map((k) => k.replace(ESCAPE, "\\$&").replace(/\s+/g, "\\s+"))
      .join("|")})\\b`,
    "i",
  ),
}));

/**
 * Best-effort category detection from a description string.
 * Returns null when no rule matches (caller should keep the current category).
 */
export function detectCategory(description: string): CategoryKey | null {
  const trimmed = description.trim();
  if (trimmed.length < 2) return null;
  for (const rule of COMPILED) {
    if (rule.pattern.test(trimmed)) return rule.category;
  }
  return null;
}
