/**
 * Drizzle schema — single source of truth for the EasySplits data model.
 *
 * Tables:
 *   profiles          — extends Supabase auth.users with display name + avatar
 *   groups            — a shared expense group (trip, household, etc.)
 *   group_members     — junction: which users belong to which group
 *   expenses          — one expense within a group
 *   expense_splits    — per-person share for a single expense
 *   settlements       — recorded payment between two members
 *   events            — append-only event log for offline sync replay
 *
 * Conventions:
 *   - Money stored in `numeric(14, 2)` (paisa-precise, supports up to 99 crore)
 *   - All tables have created_at and most have updated_at
 *   - Soft-delete via deleted_at where applicable; expenses are hard-deleted
 *     because they're rebuildable from the event log if needed
 *   - User IDs are uuid matching Supabase auth.users.id
 */

import { sql } from "drizzle-orm";
import {
  pgTable,
  text,
  uuid,
  timestamp,
  numeric,
  varchar,
  pgEnum,
  index,
  unique,
  boolean,
  integer,
} from "drizzle-orm/pg-core";

export const splitModeEnum = pgEnum("split_mode", [
  "equal",
  "exact",
  "share",
  "percent",
]);

export const profiles = pgTable("profiles", {
  /** Matches Supabase auth.users.id (or a generated UUID for guest shadows). */
  id: uuid("id").primaryKey(),
  displayName: text("display_name").notNull(),
  avatarUrl: text("avatar_url"),
  /** True for shadow profiles created via groups.addGuest. */
  isGuest: boolean("is_guest").notNull().default(false),
  /** Set when a real auth user has claimed this shadow profile. Null otherwise. */
  claimedBy: uuid("claimed_by"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Single-use token that lets a real auth user claim a shadow profile's
 * history. Generated by the group creator and shared out-of-band (WhatsApp/
 * email/etc). Consuming the token migrates all FKs from shadow → auth user
 * and deletes the shadow.
 */
export const claimTokens = pgTable(
  "claim_tokens",
  {
    token: text("token").primaryKey(),
    shadowProfileId: uuid("shadow_profile_id").notNull(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    createdBy: uuid("created_by").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("claim_tokens_shadow_idx").on(t.shadowProfileId),
    index("claim_tokens_group_idx").on(t.groupId),
  ],
);

export const groups = pgTable(
  "groups",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    name: text("name").notNull(),
    /** Three-letter ISO 4217 currency code, e.g. INR, USD. */
    primaryCurrency: varchar("primary_currency", { length: 3 })
      .notNull()
      .default("INR"),
    /** Random 32-byte hex token for shareable invite links. */
    inviteToken: text("invite_token")
      .notNull()
      .unique()
      .default(sql`encode(gen_random_bytes(32), 'hex')`),
    createdBy: uuid("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("groups_created_by_idx").on(t.createdBy),
    index("groups_invite_token_idx").on(t.inviteToken),
  ],
);

export const groupMembers = pgTable(
  "group_members",
  {
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    userId: uuid("user_id").notNull(),
    joinedAt: timestamp("joined_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique("group_members_pk").on(t.groupId, t.userId),
    index("group_members_user_idx").on(t.userId),
  ],
);

export const expenses = pgTable(
  "expenses",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    description: text("description").notNull().default(""),
    /** Total amount paid, in the original currency. */
    amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),
    /** Original currency (3-letter ISO 4217). */
    currency: varchar("currency", { length: 3 }).notNull(),
    /** Amount converted to the group's primary currency. */
    convertedAmount: numeric("converted_amount", {
      precision: 14,
      scale: 2,
    }).notNull(),
    /** FX rate applied at entry time (1 unit of `currency` = X primary). */
    fxRate: numeric("fx_rate", { precision: 18, scale: 8 }).notNull(),
    payerId: uuid("payer_id").notNull(),
    splitMode: splitModeEnum("split_mode").notNull().default("equal"),
    /** Predefined category key — see src/lib/categories.ts. */
    category: text("category").notNull().default("other"),
    occurredAt: timestamp("occurred_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdBy: uuid("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("expenses_group_idx").on(t.groupId),
    index("expenses_payer_idx").on(t.payerId),
  ],
);

export const expenseSplits = pgTable(
  "expense_splits",
  {
    expenseId: uuid("expense_id")
      .notNull()
      .references(() => expenses.id, { onDelete: "cascade" }),
    userId: uuid("user_id").notNull(),
    /** Amount this user is responsible for, in the group's primary currency. */
    amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),
  },
  (t) => [
    unique("expense_splits_pk").on(t.expenseId, t.userId),
    index("expense_splits_user_idx").on(t.userId),
  ],
);

/**
 * Itemized bill split: one expense can carry many line items, each with
 * its own subset of group members sharing that line. The expense's
 * `expense_splits` rows are still the source of truth for "what each
 * member owes" — they're computed server-side from items when items are
 * provided. Items live alongside as a record so the breakdown can be
 * shown back to the user.
 *
 * sharerIds is a uuid[] (Postgres array) instead of a junction table —
 * we never query "items where I'm a sharer" across expenses, so the
 * extra normalization buys us nothing.
 */
export const expenseItems = pgTable(
  "expense_items",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    expenseId: uuid("expense_id")
      .notNull()
      .references(() => expenses.id, { onDelete: "cascade" }),
    description: text("description").notNull().default(""),
    /** Item amount in the expense's original currency. */
    amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),
    /** Group members sharing this item — splits equally between them. */
    sharerIds: uuid("sharer_ids").array().notNull().default(sql`'{}'::uuid[]`),
    /** Display order; client emits sequential positions on save. */
    position: integer("position").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("expense_items_expense_idx").on(t.expenseId)],
);

export const expenseComments = pgTable(
  "expense_comments",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    expenseId: uuid("expense_id")
      .notNull()
      .references(() => expenses.id, { onDelete: "cascade" }),
    userId: uuid("user_id").notNull(),
    body: text("body").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("expense_comments_expense_idx").on(t.expenseId),
  ],
);

export const settlements = pgTable(
  "settlements",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    fromUserId: uuid("from_user_id").notNull(),
    toUserId: uuid("to_user_id").notNull(),
    /** Amount transferred, in the group's primary currency. */
    amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),
    note: text("note").default(""),
    occurredAt: timestamp("occurred_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("settlements_group_idx").on(t.groupId),
    index("settlements_from_idx").on(t.fromUserId),
    index("settlements_to_idx").on(t.toUserId),
  ],
);

/**
 * Append-only log for offline-edit replay + audit. Every mutation that
 * happens client-side or server-side gets an event row. Server is source
 * of truth; client replays its queued events on reconnect.
 */
export const events = pgTable(
  "events",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    groupId: uuid("group_id").references(() => groups.id, { onDelete: "cascade" }),
    /** Optional foreign-keyless reference to the expense this event affects. Survives expense deletion so audit trail is preserved. */
    expenseId: uuid("expense_id"),
    /** Type of event, e.g. "expense.added" / "expense.updated" / "expense.deleted" / "settlement.recorded". */
    eventType: text("event_type").notNull(),
    actorId: uuid("actor_id").notNull(),
    /** Snapshot of the change. JSON-encoded payload. */
    payload: text("payload").notNull(),
    /** Client-supplied UUID for idempotent replay (deduplicates retries). */
    clientEventId: uuid("client_event_id").unique(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("events_group_idx").on(t.groupId),
    index("events_actor_idx").on(t.actorId),
    index("events_occurred_idx").on(t.occurredAt),
    index("events_expense_idx").on(t.expenseId),
  ],
);

export type Profile = typeof profiles.$inferSelect;
export type Group = typeof groups.$inferSelect;
export type GroupMember = typeof groupMembers.$inferSelect;
export type Expense = typeof expenses.$inferSelect;
export type ExpenseSplit = typeof expenseSplits.$inferSelect;
export type ExpenseItem = typeof expenseItems.$inferSelect;
export type ExpenseComment = typeof expenseComments.$inferSelect;
export type Settlement = typeof settlements.$inferSelect;
export type Event = typeof events.$inferSelect;
export type ClaimToken = typeof claimTokens.$inferSelect;

/**
 * Web Push subscriptions. One row per (user, browser/device); a single
 * user can have many. Endpoint is the unique URL the push service issues
 * for a subscription — used as the natural key.
 */
export const pushSubscriptions = pgTable(
  "push_subscriptions",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    userId: uuid("user_id").notNull(),
    endpoint: text("endpoint").notNull().unique(),
    p256dh: text("p256dh").notNull(),
    auth: text("auth").notNull(),
    /** What this subscription wants to be notified about. JSON-encoded. */
    preferences: text("preferences").notNull().default("{}"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    lastNotifiedAt: timestamp("last_notified_at", { withTimezone: true }),
  },
  (t) => [index("push_subscriptions_user_idx").on(t.userId)],
);

export type PushSubscriptionRow = typeof pushSubscriptions.$inferSelect;

/**
 * Personal Finance Tracker (Phase 2.5 v1). Track-your-own income +
 * expenses + investments, separately from group splitting.
 *
 * v1.0 stores values in plaintext. Field-level encryption (Option B,
 * pgcrypto.PGP_SYM_ENCRYPT) ships in v1.1 — when it does, the
 * onboarding copy can promise "encrypted at the field level". Until
 * then the UI claims nothing about encryption.
 */
export const personalEntries = pgTable(
  "personal_entries",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    userId: uuid("user_id").notNull(),
    /** 'income' | 'expense' | 'investment' — strings rather than enum so
     *  we can extend without an ALTER TYPE migration. */
    type: text("type").notNull(),
    /** Encrypted amount (AES-256-GCM, base64). See src/lib/encryption.ts.
     *  Type column is text since the wire format is base64 — Postgres
     *  never sees the numeric value. Server decrypts before any math. */
    amount: text("amount").notNull(),
    currency: varchar("currency", { length: 3 }).notNull().default("INR"),
    /** Reuses the existing categories module — see src/lib/categories.ts.
     *  Income / investment / tax are added as keys for PFT. */
    category: text("category").notNull().default("other"),
    /** Encrypted description (same scheme as amount). Plaintext "" is
     *  also encrypted so server doesn't have to special-case empty. */
    description: text("description").notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** Soft delete — keep the row so monthly comparisons stay stable. */
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("personal_entries_user_idx").on(t.userId),
    index("personal_entries_occurred_idx").on(t.occurredAt),
  ],
);

export type PersonalEntry = typeof personalEntries.$inferSelect;

/**
 * Financial profile — backs the 5-pillar Financial Health Scorecard
 * (Phase 2.5 v3). One row per user (UNIQUE(user_id)).
 *
 * Sensitive amount columns are encrypted at the application layer using
 * the same AES-256-GCM helper as personal_entries. Demographic flags
 * (age, freelancer, dependents, has_cc_carryover) stay plaintext —
 * they're not value-sensitive and we may want to filter on them.
 *
 * All amount columns are nullable so the wizard can save partial
 * progress between steps.
 */
export const financialProfiles = pgTable(
  "financial_profiles",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid("user_id").notNull().unique(),

    // Demographic — plaintext, not value-sensitive.
    age: integer("age"),
    /** Target retirement age. Drives the investing-pillar glide path —
     *  earlier retire = steeper target. Defaults to 60 if null. */
    retirementAge: integer("retirement_age"),
    isFreelancer: boolean("is_freelancer").notNull().default(false),
    hasDependents: boolean("has_dependents").notNull().default(false),
    hasCcCarryover: boolean("has_cc_carryover").notNull().default(false),

    // Money flow — encrypted.
    monthlyIncome: text("monthly_income"),
    monthlyExpenses: text("monthly_expenses"),
    liquidSavings: text("liquid_savings"),

    // Insurance — encrypted.
    termCoverAmount: text("term_cover_amount"),
    healthCoverAmount: text("health_cover_amount"),

    // Debt + investing — encrypted.
    totalEmi: text("total_emi"),
    investmentBalance: text("investment_balance"),
    monthlyInvestment: text("monthly_investment"),

    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
);

export type FinancialProfile = typeof financialProfiles.$inferSelect;

/**
 * Append-only history of the Financial Health Score (Phase 2.5 v4).
 * Written on every profile.upsert with markCompleted=true. Powers the
 * trajectory chart, the "+12 since last month" delta, and the streak
 * badge ("3 months in the green band").
 *
 * pillar_scores stored as JSON-encoded text — same convention as the
 * events table — so we can extend the pillar set without an ALTER
 * COLUMN migration.
 */
export const scoreSnapshots = pgTable(
  "score_snapshots",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid("user_id").notNull(),
    /** 0..100 */
    total: integer("total").notNull(),
    /** "red" | "amber" | "emerald" | "green" */
    band: text("band").notNull(),
    /** JSON: { emergency: 20, insurance: 8, debt: 20, savingsRate: 20, investing: 13 } */
    pillarScores: text("pillar_scores").notNull(),
    snapshottedAt: timestamp("snapshotted_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("score_snapshots_user_idx").on(t.userId),
    index("score_snapshots_user_at_idx").on(t.userId, t.snapshottedAt),
  ],
);

export type ScoreSnapshot = typeof scoreSnapshots.$inferSelect;

/**
 * Financial goals (Phase 2.5 v4.2). User-defined milestones tied to
 * either a single pillar score (0..20) or the total score (0..100).
 *
 * Why pillar/total scores rather than raw money targets? Three reasons:
 *   1. No encryption boundary — target_score is not value-sensitive.
 *   2. Progress is trivially derived from existing score_snapshots.
 *   3. Side-steps "what currency, what unit" UX ("₹15L health cover" vs
 *      "20% savings rate" vs "6 months emergency fund") — every pillar
 *      already encodes those rules of thumb in its 0..20 scoring.
 *
 * goalKind:
 *   "pillar" — target_score is 0..20 (and pillar_key is set)
 *   "total"  — target_score is 0..100 (and pillar_key is null)
 *
 * current_value is snapshotted on every profile.upsert(markCompleted=true)
 * so we don't need to recompute scores when listing goals. completed_at
 * is auto-set the first time current_value crosses target_score.
 */
export const financialGoals = pgTable(
  "financial_goals",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid("user_id").notNull(),
    /** "pillar" | "total" */
    goalKind: text("goal_kind").notNull(),
    /** "emergency" | "insurance" | "debt" | "savingsRate" | "investing" — null when goalKind = "total" */
    pillarKey: text("pillar_key"),
    /** User-facing description — autopopulated from a template, editable. */
    label: text("label").notNull(),
    /** Pillar goals: 0..20. Total goals: 0..100. */
    targetScore: integer("target_score").notNull(),
    /** Optional self-imposed deadline. Used to compute "behind/on track". */
    targetDate: timestamp("target_date", { withTimezone: true }),
    /** Latest known score for this pillar/total — updated on profile upsert. */
    currentValue: integer("current_value").notNull().default(0),
    /** Set the first time current_value >= target_score. */
    completedAt: timestamp("completed_at", { withTimezone: true }),
    /** Soft-archive — user dismissed the goal but we keep it for history. */
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("financial_goals_user_idx").on(t.userId),
    index("financial_goals_user_active_idx").on(t.userId, t.archivedAt),
  ],
);

export type FinancialGoal = typeof financialGoals.$inferSelect;
